### ISSUE TITLE
Kanban Board

### ISSUE THREAD

**Issue by Buyaki01** [Buyaki01/space-hub#25]
- https://github.com/Buyaki01/space-hub/projects/1
- We are 3 members: @od-c0d3r, @AnselemOdims  and @Buyaki01

**Comment by hiromataba** [comment]
Hi Team :wave: , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️

- [ ] Please add the user names of all the team members in the issue to let the reviewer know the name of participants
you can say something like this: `We are 3 members` and then you list them 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by DammyShittu** [comment]
Hi @Buyaki01 @od-c0d3r  @AnselemOdims, 

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit:

Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
